version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      typescript:
        patterns:
          - "typescript"
      all-dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - "typescript"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      all-actions:
        patterns:
          - "*"
